<a href="https://colab.research.google.com/github/sitikanthaprusty2904/DL_step_in/blob/main/ann_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
import pandas as pd

In [55]:
df=pd.read_csv('/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [56]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [57]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1              False   
1               1        112542.58       0              False   
2               0        113931.57       1              False   
3               0         93826.63       0              False   
4               1         79084.10       0              False   

   Geography_Spain  Gender_Male  
0            False        False  
1             True        False  
2            False        False  
3            False        False  
4             True        False

In [58]:

X=df.drop(columns=['Exited'])
y=df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [59]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [60]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [61]:
model=Sequential()
model.add(Dense(10,activation='relu',input_dim=11))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [62]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 10)             │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 217 (868.00 B)

 Trainable params: 217 (868.00 B)

 Non-trainable params: 0 (0.00 B)

In [63]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [64]:
model.fit(X_train_scaled,y_train,epochs=50,validation_split=0.15)

Epoch 1/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6320 - loss: 0.6569 - val_accuracy: 0.7958 - val_loss: 0.4863
Epoch 2/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7975 - loss: 0.4646 - val_accuracy: 0.7958 - val_loss: 0.4516
Epoch 3/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7950 - loss: 0.4441 - val_accuracy: 0.7975 - val_loss: 0.4307
Epoch 4/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8099 - loss: 0.4228 - val_accuracy: 0.8142 - val_loss: 0.4118
Epoch 5/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8269 - loss: 0.4010 - val_accuracy: 0.8375 - val_loss: 0.3935
Epoch 6/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8307 - loss: 0.3987 - val_accuracy: 0.8467 - val_loss: 0.3777
Epoch 7/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8495 - loss: 0.3724 - val_accuracy: 0.8508 - val_loss: 0.3652
Epoch 8/50
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8522 - loss: 0.3599 - val_accuracy: 0.

In [65]:
model.layers[0].get_weights()

[array([[-6.13556653e-02, -3.31451386e-01,  1.73651204e-01,
          1.38708353e-01,  1.75036117e-01,  3.44232172e-01,
          1.06116813e-02,  1.63054049e-01, -2.68111425e-03,
          2.72109974e-02],
        [ 6.06253259e-02, -2.90366977e-01,  3.83608699e-01,
         -1.42927825e-01, -8.64754379e-01, -4.07973170e-01,
          4.32367712e-01,  3.27108264e-01,  1.17564343e-01,
         -1.06494176e+00],
        [ 1.32080078e-01, -2.22275802e-03,  7.40890950e-02,
          1.49643898e-01,  5.90172485e-02,  7.81007065e-03,
          1.83402240e-01,  3.59010249e-01,  3.12791765e-01,
         -2.70697653e-01],
        [-4.06071432e-02, -1.44512519e-01,  2.38973990e-01,
         -7.70462871e-01, -5.32065344e-04,  3.37829649e-01,
          2.52043724e-01, -8.16657662e-01, -1.24242909e-01,
          1.98639050e-01],
        [ 7.78032422e-01, -1.58937842e-01, -7.93069303e-01,
         -9.12227392e-01,  4.24573421e-02,  1.18185151e+00,
          1.00204325e+00, -9.41403285e-02, -2.075023

In [66]:
model.layers[1].get_weights()

[array([[ 0.01692825,  0.58298004,  0.05717181, -0.07648921, -0.27473488,
         -0.5001464 ,  0.66689914,  0.46973133],
        [-0.37923962, -0.0586291 ,  0.5237612 ,  0.13852412,  0.52552974,
          0.3397332 ,  0.4207453 ,  0.26131862],
        [-0.02877166, -0.32221812, -0.38052866, -0.20297264,  0.3921249 ,
          0.29270792, -0.5935876 ,  0.40181485],
        [-0.42093584,  0.04302547, -0.21628113, -0.7173626 , -0.3454867 ,
          0.4866373 ,  0.1657912 ,  0.20818849],
        [ 0.45197508,  0.3787387 ,  0.21781409,  0.74420166, -0.21850507,
         -0.6347712 , -0.59780604, -0.95221245],
        [-0.40620804,  0.25883007, -0.42684504, -0.35137552,  0.53220695,
         -0.00315978,  0.8748719 ,  0.376616  ],
        [ 0.5188995 , -0.9270508 ,  0.3253717 , -0.22252335,  0.67150956,
         -1.0193796 ,  0.7492545 ,  0.34342724],
        [ 0.69438225, -0.3364459 ,  0.479643  , -0.5172541 ,  0.7672778 ,
          0.46944678, -0.22411844,  0.16571258],
        [ 0.1914

In [67]:
model.layers[2].get_weights()

[array([[-0.51306796],
        [-1.3896596 ],
        [-1.0073485 ],
        [ 1.2686614 ],
        [-0.3376536 ],
        [ 1.0469896 ],
        [ 0.98724467],
        [ 0.6355673 ]], dtype=float32),
 array([-0.03297877], dtype=float32)]

In [68]:
y_pred=model.predict(X_test_scaled)
y_pred=np.where(y_pred>0.5,1,0)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [69]:
np.unique(y_pred,return_counts=True)

(array([0, 1]), array([1758,  242]))

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8635